version: "3.2"
services:
  api:
    image: fast_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - model
    volumes:
      - ./api:/src  # Mount local `api` folder for hot reloading
      - ./uploads:/src/uploads
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
      SECRET_KEY: $SECRET_KEY
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    networks:
      - shared_network

  redis:
    image: redis:6.2.6
    networks:
      - shared_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared_network

  model:
    image: ml_service
    container_name: ml_service
    build:
      context: ./model
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    volumes:
      - ./model:/src  # Mount local `model` folder if needed for development
      - ./uploads:/src/uploads
    networks:
      - shared_network
    command: find /src -name "*.py" | entr -r 'pkill -f ml_service.py || true && python3 -u /src/ml_service.py'

  nextjs_ui:
    image: nextjs_ui
    container_name: nextjs_ui
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=5000
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
